# Activer ce profil avec: -Dspring-boot.run.profiles=sqlserver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=operix;encrypt=false;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=operix_app
spring.datasource.password=OperixDev123!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

